keys:
  - &desktop age1xsuyaeehzv4ar4f6xpc6tfp9pttzjf7qdyl3x2tj42vjc8szlqpq834e3d
  - &laptop age1syaxvec0zg07sxpllvenzflh9clf82u05hz40pq6mh42zczlwdrqa7jdvl
  - &win10 age1cz006hex596lmj88kkhrkvq89luqk59hxuq83q4kvhz82ltwpe4ss8gm3t
  - &serverpc age1sn4uu6r6wrylpznx75jcw7ww58r9cut35n40gu4scpt9xy79rgrq2d7wga
  - &desktopWsl age13mlkm4t2gasf3409syn5xuarja63rukx937e4p3msyzg8x9ayp4se9nz2r
creation_rules:
  - path_regex: .ini
    key_groups:
    - age:
        - *desktop
        - *laptop
        - *win10
        - *serverpc
  - path_regex: .pem$
    key_groups:
    - age:
        - *desktop
        - *laptop
        - *win10
        - *serverpc
  - path_regex: .conf
    key_groups:
    - age:
        - *desktop
        - *laptop
        - *win10
        - *serverpc
  - path_regex: .sh$
    key_groups:
    - age:
        - *desktop
        - *laptop
        - *win10
        - *serverpc
  - path_regex: .env$
    key_groups:
    - age:
        - *desktop
        - *laptop
        - *win10
        - *serverpc
  - path_regex: secrets/hosts
    key_groups:
      - age:
        - *desktop
        - *laptop
        - *win10
        - *serverpc
        - *desktopWsl
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *desktop
        - *laptop
        - *win10
        - *serverpc
        - *desktopWsl
