services:
  sonarr: 
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=108
      - PGID=1002
      - TZ=America/New_York
    volumes:
      - /storage/sonarrConf:/config
      - /storage/tv:/storage/tv
      - /storage/downloads:/storage/downloads
    ports:
      - 8989:8989
    restart: unless_stopped
