github.com:
    oauth_token: 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
    user: sadanslargehole
    git_protocol: ssh
    users:
        sadanslargehole:
            oauth_token: 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
