services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=107
      - PGID=1002
      - TZ=America/New_York
    volumes:
      - /storage/radarrConf:/config
      - /storage/movies:/storage/movies
      - /storage/downloads:/storage/downloads
    ports:
      - 7878:7878
