version: '2.1'
services:
  couchdb:
    build: .
    container_name: obsidian_livesync
    env_file: ./couchdb.env
    restart: unless-stopped
    volumes:
      # state, create an empty dir
      - ./data:/opt/couchdb/data
      # config, encrypted because it has a hashed password
      - ./docker.ini:/opt/couchdb/etc/local.d/docker.ini
    ports:
      - "5984:5984"

