version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    env_file: ./vw.env
    container_name: vaultwarden
    restart: always
    ports:
      - 3231:80
    volumes:
      - ./vw-data:/data

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    env_file: ./backup.env
    volumes:
      - ./vw-data:/bitwarden/data/
      - ./rclone-config:/config/
    #   - /path/to/env:/.env

